version: "3.8"

networks:
  net:
    driver: overlay
    attachable: true

services:
  statsd-exporter:
      image: ${REGISTRY_ADDR}prom/statsd-exporter:v0.26.0
      ports:
        - "9102:9102"
      volumes:
        - ./statsd_mapping.yaml:/tmp/statsd_mapping.yaml
      command:
        - --statsd.mapping-config=/tmp/statsd_mapping.yaml
        
  node-exporter:
    image: ${REGISTRY_ADDR}prom/node-exporter:v1.7.0
    networks:
      - net
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    image: ${REGISTRY_ADDR}bitnami/prometheus:2.50.0
    networks:
      - net
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION:-24h}'
    volumes:
      - prometheus:/prometheus
    configs:
      - source: prom_scrape_conf
        target: /etc/prometheus/prometheus.yaml
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yaml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yaml
    ports:
      - 9090:9090
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M

  dockerd-exporter:
    image: ${REGISTRY_ADDR}stefanprodan/caddy:0.10.10
    networks:
      - net
    environment:
      - DOCKER_GWBRIDGE_IP=172.18.0.1
    configs:
      - source: dockerd_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor:
    image: ${REGISTRY_ADDR}gcr.io/cadvisor/cadvisor:v0.49.1
    networks:
      - net
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /proc:/host/proc:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

configs:
  dockerd_config:
    file: ./dockerd-exporter/Caddyfile
  prom_scrape_conf:
    file: ./prometheus/prometheus.yaml
  node_rules:
    file: ./prometheus/rules/swarm_node.rules.yaml
  task_rules:
    file: ./prometheus/rules/swarm_task.rules.yaml

volumes:
    prometheus: {}